site_name: PDSurvey Platform
repo_url: https://github.com/lukasziegler/masterarbeit/
theme: readthedocs
pages:
- ['index.md', 'PDSurvey']
- ['developer/index.md', 'Developers']
- ['developer/architecture.md', 'Architecture']
- ['maintenance/index.md', 'Maintenance']
- ['user/index.md', 'Users']
